rails-skeleton/config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :answers
    resources :comments
  end

  resources :answers, only: [:index] do
    resources :comments
  end

  root "questions#index"
end

rails-skeleton/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to  :user
  belongs_to :question
  has_many   :comments, as: :commentable

  validates_presence_of :body, :answerer, :user_id
end

rails-skeleton/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-skeleton/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to  :user
  belongs_to :commentable, polymorphic: true

  validates_presence_of :body, :commenter, :user_id
end

rails-skeleton/app/models/question.rb
class Question < ApplicationRecord
  belongs_to  :user
  has_many :answers
  has_many :comments, as: :commentable

  validates_presence_of :title, :body, :user_id
end

rails-skeleton/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many  :questions
  has_many  :answers
  has_many  :comments
  validates :username, :email, { presence: true }
  validates :email, { uniqueness: true }
  # validate :check_password

  # def check_password
  #   if @raw_password == ""
  #     @errors.add(:password, "needs to be 8 characters or more")
  #   end
  # end

  # def self.authenticate(email, raw_password)
  #   user = User.find_by(email: email)
  #   return user if user && (user.password == raw_password)
  # end

  # def password
  #   @password ||= BCrypt::Password.new(hashed_password)
  # end

  # def password=(new_password)
  #   @raw_password = new_password
  #   @password = BCrypt::Password.create(@raw_password)
  #   self.hashed_password = password
  # end


end

rails-skeleton/app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    redirect_to @question
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])

    if @answer.update(answer_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to @question
  end

  private
  def answer_params
    params.require(:answer).permit(:answerer, :body)
  end

end

rails-skeleton/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails-skeleton/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    p params
    p klass = params[:commentable_type].capitalize.constantize
    @commenter = klass.find(params[:commentable_id])
    @comment = @commenter.comments.create(comment_params)
    if klass == Question
      redirect_to @commenter
    elsif klass == Answer
      redirect_to @commenter.question
    end
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :commentable_type, :commentable_id)
  end

end

rails-skeleton/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @commenter = @question
    @comment = Comment.new(commentable_type: @commenter.class, commentable_id: @commenter.id)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to root_path
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end

end

rails-skeleton/app/controllers/users_controller.rb
class UsersController < ApplicationController
  private
  def user_params
    params.require(:user).permit()
  end
end

rails-skeleton/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-skeleton/app/views/answers/_answer.html.erb
<p>
  <strong>Answerer:</strong>
  <%= answer.answerer %>
</p>

<p>
  <strong>Answer:</strong>
  <%= answer.body %>
</p>

<p>
  <%= link_to 'Edit Answer', edit_question_answer_path(answer.question, answer) %>
  <%= link_to 'Delete Answer', [answer.question, answer],
                                method: :delete,
                                data: { confirm: "Forreal?" } %>

</p>

<h4>Answer Comments</h4>
<%= render answer.comments %>

<h2>Add a comment: </h2>
  <%= render 'comments/form' %>

rails-skeleton/app/views/answers/_form.html.erb
<%= form_for ([@question, @answer]) do |f| %>

  <p>
    <%= f.label :answerer %><br>
    <%= f.text_field :answerer %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

rails-skeleton/app/views/answers/edit.html.erb
<h1>Edit this answer</h1>

<%= render 'form' %>

rails-skeleton/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

rails-skeleton/app/views/comments/_form.html.erb
<%= form_for ([@commenter, @comment]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
    <p>Comment type is: <%= @comment.commentable_type %></p>
  </p>

<% end %>

rails-skeleton/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stack Overflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= link_to "home", root_path %></p>
    <%= yield %>
  </body>
</html>

rails-skeleton/app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

rails-skeleton/app/views/questions/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

rails-skeleton/app/views/questions/index.html.erb
<h1>Questions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= link_to question.title, question_path(question) %></td>
      <td><%= question.body %></td>
      <td><%= link_to "Edit", edit_question_path(question) %></td>
      <td><%= link_to "Delete", question_path(question),
          method: :delete,
          data: { confirm: "Fo sho?" } %></td>
    </tr>
  <% end %>
</table>

<%= link_to "New Question", new_question_path %>

rails-skeleton/app/views/questions/new.html.erb
<h1>New</h1>

<%= render 'form' %>

rails-skeleton/app/views/questions/show.html.erb
<p>
  <strong>Title: </strong>
  <%= @question.title %>
</p>

<p>
  <strong>Body: </strong>
  <%= @question.body %>
</p>

<h4>Question Comments: </h4>
  <%= render @question.comments %>

<h4>Add a comment: </h4>
  <%= render 'comments/form' %>

<h2>Answers: </h2>
  <%= render @question.answers %>

<h2>Add an answer: </h2>
  <%= render 'answers/form' %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>